models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata data.json && mod_wsgi-express start-server --working-directory . --reload-on-changes ./project/wsgi.py"