# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalshopper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalshopper.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(default='US', max_length=100),
        ),
    ]
