# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalshopper', '0002_auto_20170915_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
